//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OracleEfTest.WMSTakModelFirst
{
    using System;
    using System.Collections.Generic;

    //[Table("WMS.WMS_PrinthHstoryTable")]
    public partial class WMS_PrinthHstoryTable
    {
        [Key]
        [StringLength(36)]
        public string PrintId { get; set; }

        [StringLength(16)]
        public string ContainerCode { get; set; }

        public int? PrintType { get; set; }

        public int? TaskType { get; set; }

        [StringLength(32)]
        public string MaterialsCode { get; set; }

        [StringLength(64)]
        public string MaterialsName { get; set; }

        [StringLength(32)]
        public string Model { get; set; }

        [StringLength(32)]
        public string PackModel { get; set; }

        [StringLength(32)]
        public string MaterialsAttribute { get; set; }

        [StringLength(32)]
        public string ProductBatch { get; set; }


        public decimal? Quantity { get; set; }

        [StringLength(64)]
        public string ProductName { get; set; }

        [StringLength(10)]
        public string MatureDate { get; set; }

        [StringLength(1000)]
        public string Remark { get; set; }

        public int? Attribute1 { get; set; }

        [StringLength(32)]
        public string Attribute2 { get; set; }

        [StringLength(80)]
        public string Attribute3 { get; set; }

        public DateTime? CreateDate { get; set; }

        [StringLength(36)]
        public string CreateUserId { get; set; }

        [StringLength(50)]
        public string CreateUserName { get; set; }

        public DateTime? ModifyDate { get; set; }

        [StringLength(36)]
        public string ModifyUserId { get; set; }

        [StringLength(50)]
        public string ModifyUserName { get; set; }
    }
}
